module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Safty',
    'Funny',
    'Fridenly',
    'Restroom',
    'Fountain',
    'Merry-Go-Round',
    'Teeter-Totter',
    'Giant Stride',
    'Monkey Bars',
    'Still Rings',
    'Swings',
    'Slides',
    'Playground Climbers',
    'Spring Riders',
    'Spinners',
    'Sensory Panels'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Shopping mall',
    'National park',
    'County Park',
    'Water Park',
    'School',
    'Daycare',
    'Community center',
    'Mall',
    'Zoo',
    'Aquarium',
    'Science museum',
    'Amusement park',
    'Backyard'
]
